development:
  adapter: postgresql
  encoding: unicode
  database: summerLeague
  username: aiwen
  password: aiwen

test:
  adapter: postgresql
  encoding: unicode
  database: summerLeague
  username: aiwen
  password: aiwen
  
production:
  adapter: postgresql
  encoding: unicode
  database: summerLeague
  username: aiwen
  password: aiwen

