development:
  adapter: postgresql
  encoding: unicode
  database: genetic_dev
  username: dano
  password: danielko
 
test:
  adapter: postgresql
  encoding: unicode
  database: genetic_dev
  username: dano
  password: danielko

production:
  adapter: postgresql
  encoding: unicode
  database: genetic_dev
  username: dano
  password: danielko
