development:
  adapter: postgresql
  encoding: unicode
  database: genetic_dev
  username: dusan
  password: waldinko
 
test:
  adapter: postgresql
  encoding: unicode
  database: genetic_dev
  username: dusan 
  password: waldinko

production:
  adapter: postgresql
  encoding: unicode
  database: genetic_dev
  username: dusan
  password: waldinko
